In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/mihirshah/Desktop/DATASETS/Generation_Data.csv')
df.drop(['PLANT_ID'], axis = 1, inplace = True)
df.drop(['DATE_TIME'], axis = 1, inplace = True)


DC_POWER = df['DC_POWER']
AC_POWER = df['AC_POWER']
DAILY_YIELD = df['DAILY_YIELD']
TOTAL_YIELD = df['TOTAL_YIELD']

df['SOURCE_KEY'] = df['SOURCE_KEY'].astype('object') 
df['DC_POWER'] = df['DC_POWER'].astype('int64') 
df['AC_POWER'] = df['AC_POWER'].astype('int64') 
df['DAILY_YIELD'] = df['DAILY_YIELD'].astype('int64') 
df['TOTAL_YIELD'] = df['TOTAL_YIELD'].astype('int64')   
df.drop(['DC_POWER', 'AC_POWER' ,'DAILY_YIELD', 'TOTAL_YIELD'], axis = 1, inplace = True)

df.head(5)

        SOURCE_KEY
0  4UPUqMRk7TRMgml
1  81aHJ1q11NBPMrL
2  9kRcWv60rDACzjR
3  Et9kgGMDl729KT4
4  IQ2d7wF4YD8zU1Q

In [ ]:
# x = dataset.iloc[:, 0:-1].values
# y = dataset.iloc[:, -1].values

In [ ]:
#dataset['SOURCE_KEY'].value_counts()

In [ ]:
dataset = pd.get_dummies(df)

In [ ]:
dataset['DC_POWER'] = DC_POWER
dataset['AC_POWER'] = AC_POWER
dataset['DAILY_YIELD'] = DAILY_YIELD
dataset['TOTAL_YIELD'] = TOTAL_YIELD


dataset['DC_POWER'] = dataset['DC_POWER'].astype('int64') 
dataset['AC_POWER'] = dataset['AC_POWER'].astype('int64') 
dataset['DAILY_YIELD'] = dataset['DAILY_YIELD'].astype('int64') 
dataset['TOTAL_YIELD'] = dataset['TOTAL_YIELD'].astype('int64')  
dataset.to_csv('/Users/mihirshah/Desktop/DATASETS/Generation_Data(123).csv')
dataset

,SOURCE_KEY_4UPUqMRk7TRMgml,SOURCE_KEY_81aHJ1q11NBPMrL,SOURCE_KEY_9kRcWv60rDACzjR,SOURCE_KEY_Et9kgGMDl729KT4,SOURCE_KEY_IQ2d7wF4YD8zU1Q,SOURCE_KEY_LYwnQax7tkwH5Cb,SOURCE_KEY_LlT2YUhhzqhg5Sw,SOURCE_KEY_Mx2yZCDsyf6DPfv,SOURCE_KEY_NgDl19wMapZy17u,SOURCE_KEY_PeE6FRyGXUgsRhN,...,SOURCE_KEY_oZZkBaNadn6DNKz,SOURCE_KEY_q49J1IKaHRwDQnt,SOURCE_KEY_rrq4fwE8jgrTyWY,SOURCE_KEY_vOuJvMaM2sgwLmb,SOURCE_KEY_xMbIugepa2P7lBB,SOURCE_KEY_xoJJ8DcxJEcupym,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,9425,2429011
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1215278736
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3075,2247719577
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,269,1704250
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3177,19941526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67693,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,4157,520758
67694,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,3931,121131356
67695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,4322,2427691
67696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,4218,106896394
67697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,4316,209335741

In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
y = y.reshape(len(y), 1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [ ]:
#from sklearn.preprocessing import StandardScaler
#sc_x = StandardScaler()
#x_train[:, 23:] = sc_x.fit_transform(x_train[:, 23:])
#x_test[:, 23:] = sc_x.fit_transform(x_test[:, 23:])

In [ ]:
#from sklearn.preprocessing import StandardScaler
#sc_y = StandardScaler()
#y_train[:] = sc_y.fit_transform(y_train[:])
#y_test[:] = sc_y.fit_transform(y_test[:])

## Training the Regression model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(x_train, y_train)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [ ]:
y_pred = regressor.predict(x_test)
y_pred = y_pred.astype('int64')
y_test = y_test.astype('int64')
y_pred1 = y_pred.reshape(len(y_pred), 1)
y_test1 = y_test.reshape(len(y_test), 1)
a = np.concatenate((y_pred1, y_test1), 1)
am = pd.DataFrame(data  = a, columns = ('Predicted Value', 'Real Value'))
am.to_csv('/Users/mihirshah/Desktop/DATASETS/Generation_Data(123).csv')

#### r^2 Metrics to evaluate models performance

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.983135542470937